### ISSUE TITLE
Some of the _ORANGE or _RED sprites actually have black backgrounds

### ISSUE THREAD

**Issue by 27escape** [Roemer/plantuml-office#2]
for example

cloud_disater_red

!define OFF_CLOUD_DISASTER_RED(_alias) ENTITY(rectangle,black,cloud_disaster_red,_alias,OFF CLOUD_DISASTER_RED)

home_orange
!define OFF_HOME_ORANGE(_alias) ENTITY(rectangle,black,home_orange,_alias,OFF HOME_ORANGE)

My personal preference would not to have specific colored ones, just to direct us users to use the full macro with shape and color when we want something specific

Many thanks for this extra plantUML add in, I hope it gets added to the core code
kevin

**Comment by 27escape** [comment]
Also you only get a white background on CLOUD_DISATER_RED if I set the shape to be a folder as the default shape in your macro is rectangle and not folder - the skinparam sets the folder color,, it would be better setting the rectangle color

**Comment by Roemer** [comment]
Thanks for your feedback!
I used https://github.com/tupadr3/plantuml-icon-font-sprites as template and even use the same common.

Regarding the colors: The problem is that the sprites are only monchrome/transparent, so there is no difference in the colored ones when using the sprites. But if you use the png with the img tag, you can use the colored ones. As all files are automatically generated, I just kept the pumls for the useless colored ones.

Regarding the skinparam: Again I used the same as from https://github.com/tupadr3/plantuml-icon-font-sprites as I do not fully understand PlantUML yet. Maybe I should remove the skinparam completely? Then the user can fully decide how he wants to color it (easiest by using #<color> at the end of the makro). What do you think?

**Comment by 27escape** [comment]
Hi Roemer,
Personally I would leave it to the user to chose the color, I use the material and fontawesome sprites like this without any issue, the AWS have colour built in so I do not use them as much.

If you use the following

@startuml
package "Sprites" {
    OFF_DATABASE_SERVER( db, DB, rectangle, darkred) #WHITE
    OFF_APPLICATION_SERVER( app, App-Server, node)
    OFF_FIREWALL_ORANGE( fw, Firewall, rectangle, red) #WHITE
    OFF_CLOUD_DISASTER_RED( notred_cloud, Cloud)
    OFF_CLOUD_DISASTER_RED( redcloud, Cloud, rectangle, red)
    OFF_CLOUD_DISASTER_RED( redcloudfolder, Cloud, folder, red)
    db <-> app
    app <--> fw
    fw <.left.> notred_cloud
    redcloud -> notred_cloud
    redcloudfolder -> notred_cloud
}
@enduml

if you want to change the macro for the red and orange sprites then you can add the red/orange and the shapes directly into them as defaults

!define OFF_CLOUD_DISASTER_RED(_alias) ENTITY(rectangle,**red**,cloud_disaster_red,_alias,OFF CLOUD_DISASTER_RED)
!define OFF_CLOUD_DISASTER_RED(_alias,_label) ENTITY(rectangle,black,cloud_disaster_red,_label,_alias,OFF CLOUD_DISASTER_RED)
!define OFF_CLOUD_DISASTER_RED(_alias,_label,_shape) ENTITY(_shape,black,cloud_disaster_red,_label,_alias,OFF CLOUD_DISASTER_RED)
!define OFF_CLOUD_DISASTER_RED(_alias,_label,_shape,_color) ENTITY(_shape,_color,cloud_disaster_red,_label,_alias,OFF CLOUD_DISASTER_RED)
skinparam **rectangle**BackgroundColor<<OFF CLOUD_DISASTER_RED>> White

I think the above _should_ work

**Comment by Roemer** [comment]
Please check my latest commit.
I've removed the skinparam completely and added one more example on how to color the things. Also I added some text why the ..._red and such sprites exist although they are still black.
Would that work for you?

**Comment by Roemer** [comment]
Closed due to inactivity.
